title: Yuchen Sun
description: Gradute student at Department of Earth and Planetary Science, the University of Tokyo
show_downloads: false

baseurl: "" # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "https://sonyuushin.com" # change this to the base hostname & protocol for your site



# social
author: Sun



header_page_refs: ['zhongwen', 'cv', 'research', 'achievements','contact']
